# Introduccion

![](../img/c1.PNG)

El método de Cramer establece lo siguiente:

Sea A una matriz de nxn y suponga que **det𝐴≠0**. Si A es la matriz de coeficientes de un sistema de ecuaciones lineales, la solución única al sistema está dada por:

![](../img/c2.PNG)

## Sistema de ecuaciones

![](../img/c3.PNG)

A partir de este sistema surgen las siguientes determinantes:

![](../img/c4.PNG)



Ya calculados los valores D1,D2, D3 y de D se sustituyen para obtener la solución única del sistema de ecuaciones según corresponda

![](../img/c5.PNG)

## Ejemplo

Sea el siguiente sistema:

![](../img/c6.PNG)

In [5]:
import numpy as np

# Matriz de coeficientes
A = np.array([[2,4,6],[4,5,6],[3,1,-2]])

print(A)

print("")
#Matriz de resultados

B = np.array([[18],[24],[4]])

print(B)

[[ 2  4  6]
 [ 4  5  6]
 [ 3  1 -2]]

[[18]
 [24]
 [ 4]]


In [7]:
D = np.linalg.det(A).round()

D

6.0

Armamos los determinantes y los calculamos cada uno.

![](../img/c7.PNG)


In [8]:
# Matrices de determinantes

D1 = np.array([[18,4,6],[24,5,6],[4,1,-2]])
D1 = np.linalg.det(D1).round()
print(D1)

D2 = np.array([[2,18,6],[4,24,6],[3,4,-2]])
D2 = np.linalg.det(D2).round()
print(D2)

D3 = np.array([[2,4,18],[4,5,24],[3,1,4]])
D3 = np.linalg.det(D3).round()
print(D3)

24.0
-12.0
18.0


Por la Regla de Cramer, sustituimos los valores de los determinantes obtenidos en la solución única del sistema de ecuaciones.

![](../img/c8.PNG)

In [9]:
X1 = D1/D 
print("x1: ",X1)

X2 = D2/D 
print("x2: ",X2)

X3 = D3/D 
print("x3: ",X3)

x1:  4.0
x2:  -2.0
x3:  3.0
