# Metodo Gauss Jordan

El método de eliminación de Gauss-Jordan consiste en obtener la matriz identidad que contiene la solución de las ecuaciones lineales a través de las operaciones elementales entre renglones.

## Matriz

Es un arreglo rectangular de números.
Una matriz con m renglones y n columnas se llama matriz de m x n.

La matriz para el método de Gauss-Jordan se forma con los coeficientes de las variables del sistema de ecuaciones a resolver









## Matriz identidad

![](../img/12.PNG)

## Pasos para el metodo Gauss-Jordan

* Paso 1: Armar la matriz de coeficientes.
* Paso 2: Armar la matriz aumentada identificando la columna de renglones o filas para realizar las operaciones elementales entre renglones.
* Paso 3: Ya con la matriz aumentada se realizan las operaciones elementales entre renglones para obtener la matriz identidad, en donde se obtienen los resultados de las variables buscadas.








### Paso 1: Matriz de coeficientes

![](../img/10.PNG)

### Paso 2: Matriz aumentada

![](../img/11.PNG)

### Paso 3: Operaciones elementales entre renglones

![](../img/13.PNG)



## Recomendaciones para el metodo Gauss-Jordan

![](../img/14.PNG)


![](../img/15.PNG)

## Ejemplo de aplicacion

![](../img/16.PNG)

![](../img/17.PNG)

![](../img/18.PNG)

![](../img/19.PNG)


### Operaciones finales

![](../img/20.jpg)

![](../img/21.jpg)

![](../img/22.jpg)

**Finalmente, en la ultima matriz se obtiene la matriz identidad y del lado derecho las soluciones del sistema, es decir:**

```
x1=4
x2=-2
x3=3
```



## Metodo con python


In [1]:
import numpy as np

![](../img/16.PNG)

In [2]:
# Matriz coeficientes 

A = np.array([[2,4,6],[4,5,6],[3,1,-2]])

A

array([[ 2,  4,  6],
       [ 4,  5,  6],
       [ 3,  1, -2]])

In [6]:
# Matriz resultados

b = np.array([[18],[24],[4]])

b

array([[18],
       [24],
       [ 4]])

In [7]:
# Evitar truncamiento en operaciones
A = np.array(A,dtype=float) 

# Matriz aumentada
AB = np.concatenate((A,b),axis=1)
AB0 = np.copy(AB)

AB0

array([[ 2.,  4.,  6., 18.],
       [ 4.,  5.,  6., 24.],
       [ 3.,  1., -2.,  4.]])

In [9]:
# Pivoteo parcial por filas
size = np.shape(AB)
n = size[0] #Filas 
m = size[1] #Columnas

size,n,m

((3, 4), 3, 4)

In [11]:
# Para cada fila en AB
for i in range(0,n-1,1):
    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dondemax = np.argmax(columna)
    
    # dondemax no está en diagonal
    if (dondemax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dondemax+i,:]
        AB[dondemax+i,:] = temporal
        
AB1 = np.copy(AB)

AB1

array([[ 4.,  5.,  6., 24.],
       [ 2.,  4.,  6., 18.],
       [ 3.,  1., -2.,  4.]])

In [12]:
# eliminacion hacia adelante
for i in range(0,n-1,1):
    pivote = AB[i,i]
    adelante = i + 1
    for k in range(adelante,n,1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
AB2 = np.copy(AB)

AB2

array([[ 4. ,  5. ,  6. , 24. ],
       [ 0. ,  1.5,  3. ,  6. ],
       [ 0. ,  0. , -1. , -3. ]])

In [15]:
# elimina hacia atras
ultfila = n-1
ultcolumna = m-1
for i in range(ultfila,0-1,-1):
    pivote = AB[i,i]
    atras = i-1 
    for k in range(atras,0-1,-1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]
X = np.copy(AB[:,ultcolumna])
X = np.transpose([X])

X

array([[ 4.],
       [-2.],
       [ 3.]])

In [16]:
# SALIDA
print('Matriz aumentada:')
print(AB0)
print('Pivoteo parcial por filas')
print(AB1)
print('eliminacion hacia adelante')
print(AB2)
print('eliminación hacia atrás')
print(AB)
print('solución de X: ')
print(X)

Matriz aumentada:
[[ 2.  4.  6. 18.]
 [ 4.  5.  6. 24.]
 [ 3.  1. -2.  4.]]
Pivoteo parcial por filas
[[ 4.  5.  6. 24.]
 [ 2.  4.  6. 18.]
 [ 3.  1. -2.  4.]]
eliminacion hacia adelante
[[ 4.   5.   6.  24. ]
 [ 0.   1.5  3.   6. ]
 [ 0.   0.  -1.  -3. ]]
eliminación hacia atrás
[[ 1.  0.  0.  4.]
 [ 0.  1.  0. -2.]
 [-0. -0.  1.  3.]]
solución de X: 
[[ 4.]
 [-2.]
 [ 3.]]
