# Inversa de una matriz

Para este metodo tenemos que tener en cuenta dos factores:

## Eliminacion Gauss-Jordan

El método de eliminación de Gauss-Jordan consiste en obtener la matriz identidad que contiene la solución de las ecuaciones lineales, mediante las operaciones elementales por renglones.

## Operaciones elementales entre renglones

• Multiplicar (o dividir) un renglón por un número constante diferente de cero.

• Sumar un múltiplo de un renglón a otro renglón.

• Intercambiar dos renglones.



A la aplicación de estas operaciones se le conoce como reducción por renglones.



## Ejemplo

![](../img/i1.PNG)




In [1]:
import numpy as np

A = np.array([[0,1,3],[3,4,-2],[-1,5,8]])

A

array([[ 0,  1,  3],
       [ 3,  4, -2],
       [-1,  5,  8]])

### Operaciones elementales

![](../img/i2.PNG)

![](../img/i3.PNG)

![](../img/i4.PNG)

Obteniendo la inversa

![](../img/i5.PNG)




Quedando:

![](../img/i6.PNG)

In [4]:
inv = np.linalg.inv(A)

inv

array([[ 1.2       ,  0.2       , -0.4       ],
       [-0.62857143,  0.08571429,  0.25714286],
       [ 0.54285714, -0.02857143, -0.08571429]])

In [5]:
# Verificacion la A*A-1 = Matriz identidad

check = np.dot(A,inv)

check

array([[ 1.00000000e+00,  3.46944695e-18,  2.77555756e-17],
       [-6.66133815e-16,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  2.77555756e-17,  1.00000000e+00]])