# Introduccion

Las matrices son conjuntos de elementos ordenados en una estructura de filas y columnas. Dependiendo del número de filas y columnas que tenga una matriz, estaremos hablando de una dimensión u otra.



![](../img/m1.png)

## Tipos de matrices



### Matriz cuadrada

Una matriz cuadrada es una matriz que tiene el mismo número de filas que de columnas.

![](../img/m2.png)


La diagonal principal de una matriz cuadrada son los elementos que van desde la esquina superior izquierda hasta la esquina inferior derecha







In [24]:
import numpy as np

In [25]:
A = np.array([[5,2,-3],[1,9,7],[4,1,-2]])
A

array([[ 5,  2, -3],
       [ 1,  9,  7],
       [ 4,  1, -2]])

#### Propiedades

* Cualquier matriz cuadrada se puede descomponer en una suma de una matriz simétrica y una matriz antisimétrica.
* Si dos matrices cuadradas son del mismo orden, se pueden sumar o restar entre sí
* Se pueden multiplicar dos matrices cuadradas en los dos sentidos posibles. Sin embargo, el producto de matrices cuadradas no es conmutativo, es decir, el resultado de la multiplicación cambiará según el lado por el que se multiplique.
* Las matrices cuadradas son las únicas que permiten calcular el determinante. Por lo tanto, solo se puede resolver un determinante si se trata de una matriz cuadrada. 

**Si el determinante de la matriz es diferente de 0 significa que es una matriz regular, es decir, que es invertible. Por contra, si el determinante es nulo, se trata de una matriz singular (que no tiene inversa).**

In [26]:
# Suma de matrices cuadradas

B = np.array([[2,3,0],[8,6,-4],[1,3,-1]])

res = A+B

print(f'La suma de A \n {A} \n + B \n {B} es: \n')
print(res)

La suma de A 
 [[ 5  2 -3]
 [ 1  9  7]
 [ 4  1 -2]] 
 + B 
 [[ 2  3  0]
 [ 8  6 -4]
 [ 1  3 -1]] es: 

[[ 7  5 -3]
 [ 9 15  3]
 [ 5  4 -3]]


In [27]:
# Multiplicacion de matrices

C = np.array([[3,-1],[4,0]])
D = np.array([[5,2],[3,1]])

m1 = np.dot(C,D)
m2 = np.dot(D,C)

print("La matriz C es: \n",C)
print("La matriz D es: \n",D)

print("La multiplicacion de las matrices C*D es: \n",m1)

print("La multiplicacion de las matrices D*C es: \n",m2)


La matriz C es: 
 [[ 3 -1]
 [ 4  0]]
La matriz D es: 
 [[5 2]
 [3 1]]
La multiplicacion de las matrices C*D es: 
 [[12  5]
 [20  8]]
La multiplicacion de las matrices D*C es: 
 [[23 -5]
 [13 -3]]


In [28]:
# Determinante usando la regla de Sarrus
det = ((A[0][0] * A[1][1] * A[2][2]) + (A[0][1]  * A[1][2] * A[2][0]) + 
       (A[0][2] * A[1][0] * A[2][1])) - ((A[2][0] * A[1][1] * A[0][2]) + 
       (A[2][1]  * A[1][2] * A[0][0]) + (A[2][2] * A[1][0] * A[0][1]))
     
  # mostramos el resultado
print("El determinante de la matriz A es: %f" % det)

El determinante de la matriz A es: 40.000000


In [29]:
# Determinante usando numpy

print("La matriz A es: \n",A)
detA = np.linalg.det(A)
detA

La matriz A es: 
 [[ 5  2 -3]
 [ 1  9  7]
 [ 4  1 -2]]


40.0

### Matriz inversa

Transformación lineal de una matriz mediante la multiplicación del inverso del determinante de la matriz por la matriz adjunta traspuesta.

#### Propiedades

* La inversa de un producto de matrices es igual al producto de la inversa de cada matriz: (A x B)^-1 = A^-1 x B^-1
* Si una matriz es invertible, también lo es su transpuesta. El inverso de la transpuesta es la transpuesta de su inversa: 
(AT)^1 = (A^-1)^T
* La inversa de la matriz inversa es la matriz natural: (A^-1)

Existen diferentes métodos para calcular la inversa de una matriz. Si una matriz es invertible podemos calcular su inversa a partir del método por determinantes, el método de Gauss-Jordan y el método por adjuntos. Sea cual sea el método para calcular la matriz inversa, el resultado debe ser el mismo, ya que una matriz tan sólo tiene una inversa.

![](../img/m3.png)



In [31]:
# Codigo con numpy

import numpy as np

m=np.array([[3,4,-1],[2,0,1],[1,3,-2]])

inv_m = np.linalg.inv(m)

inv_m

array([[-0.6,  1. ,  0.8],
       [ 1. , -1. , -1. ],
       [ 1.2, -1. , -1.6]])

In [35]:
#Comprobamos con la multiplicacion de las dos matrices el resultado debe ser una matriz identidad

print(np.dot(inv_m, m))

print(np.eye(3))

#Comprobamos con una matriz identidad generada anteriormente
print(np.allclose(np.dot(inv_m, m), np.eye(3)))



[[ 1.00000000e+00 -1.11022302e-16  4.44089210e-16]
 [-4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
True


**Los valores python los muestra como otro valor pero se pueden redondear a 0**

### Matriz transpuesta

La matriz transpuesta (o traspuesta) de la matiz A se denota por AT y es la matriz que tiene por filas a las columnas de A.

Si la matriz  A es de dimensión mxn, entonces la dimensión de  AT  es nxm.

![](../img/m4.png)

#### Propiedades

* Si la matriz A es cuadrada y diagonal, A = AT.
* La transpuesta de la transpuesta de A es A: (AT)T = A.
* La transpuesta de la suma de matrices es (A + B)T = AT + BT.
* La transpuesta del producto de un escalar α por una matriz A es (α·A)T = α·AT
* La transpuesta del producto de matrices es (A·B)T = BT·AT.

In [37]:
#Matriz transpuesta
import numpy as np

m = ( ["a", "b", "c"], ["1", "2", "3"], ["d", "e", "f"])
print( "Matriz original:" )
print( m )

mt = np.transpose( m )
print( "\nMatriz transpuesta Python:" )
print( mt )

Matriz original:
(['a', 'b', 'c'], ['1', '2', '3'], ['d', 'e', 'f'])

Matriz transpuesta Python:
[['a' '1' 'd']
 ['b' '2' 'e']
 ['c' '3' 'f']]
