# Propiedades de la multiplicacion de matrices

![](../img/p1.PNG)

![](../img/p2.PNG)

![](../img/p3.PNG)


**La multiplicacion solo se podra hacer si:**

![](../img/p4.PNG)


![](../img/p5.PNG)

![](../img/p6.PNG)

## Ejemplo de producto de matrices

![](../img/p7.PNG)

![](../img/p8.PNG)

In [4]:
import numpy as np

In [6]:
A = np.array([[2,1,-6],[1,-3,2]])
B = np.array([[1,0,-3],[0,4,2],[-2,1,1]])

print(A)
print("")
print(B)

[[ 2  1 -6]
 [ 1 -3  2]]

[[ 1  0 -3]
 [ 0  4  2]
 [-2  1  1]]


**Ejemplo de un elemento de C**

![](../img/p9.PNG)

In [ ]:
def producto_matrices(A, B):
    filas_a = len(A)
    filas_b = len(B)
    columnas_a = len(A[0])
    columnas_b = len(B[0])
    if columnas_a != filas_b:
        return None
    # Asignar espacio al producto. Es decir, rellenar con "espacios vacíos"
    producto = []
    for i in range(filas_b):
        producto.append([])
        for j in range(columnas_b):
            producto[i].append(None)
    # Rellenar el producto
    for c in range(columnas_b):
        for i in range(filas_a):
            suma = 0
            for j in range(columnas_a):
                suma += A[i][j]*B[j][c]
            producto[i][c] = suma
    return producto

## Resultado final

![](../img/p10.PNG)

In [14]:
C = np.dot(A,B)

C

array([[ 14,  -2, -10],
       [ -3, -10,  -7]])