# Propiedades 

![](../img/s1.PNG)

![](../img/s2.PNG)

## Ejemplo en python

![](../img/s3.PNG)



In [6]:
import numpy as np



In [11]:
A = np.array([[3,0,-2],[2,-1,4]])
print(A)
print("El size de A es: ",A.shape)

B = np.array([[5,-3,6],[1,2,-5]])
print(B)
print("El size de B es: ",B.shape)

C = np.array([[5,-3]])
print(C)
print("El size de C es: ",C.shape)


[[ 3  0 -2]
 [ 2 -1  4]]
El size de A es:  (2, 3)
[[ 5 -3  6]
 [ 1  2 -5]]
El size de B es:  (2, 3)
[[ 5 -3]]
El size de C es:  (1, 2)


Suma de matrices

![](../img/s4.PNG)

In [13]:
print(A+B)

[[ 8 -3  4]
 [ 3  1 -1]]


In [12]:
# Demostracion de que no se pueden sumar matrices de diferente size

print(A+C)

#ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [17]:
# Propiedad conmutativa
# A+B = B+A

print(A+B)
print("Demostraccion que es correcta")
print(B+A)

print(np.allclose((A+B),(B+A)))
# Nos arrojara true si las dos afirmaciones son verdad


[[ 8 -3  4]
 [ 3  1 -1]]
Demostraccion que es correcta
[[ 8 -3  4]
 [ 3  1 -1]]
True


**Las matrices deben tener el mismo size para poderse sumar**

In [22]:
# Propiedad del neutro aditivo
# A+0 = 0+A = A

print(A+0)
print("")
print(0+A)
print("")
print(A)

[[ 3  0 -2]
 [ 2 -1  4]]

[[ 3  0 -2]
 [ 2 -1  4]]

[[ 3  0 -2]
 [ 2 -1  4]]


Resta de matrices

![](../img/s5.PNG)

In [19]:
V = np.array([[1,2],[3,4]])
R = np.array([[5,-1],[-6,9]])

print(V-R)

[[-4  3]
 [ 9 -5]]


Se pueden realizar operaciones usando escalares tambien

![](../img/s6.PNG)




In [32]:
A = np.array([[1,2],[4,-2]])
B = np.array([[3,-4],[7,1]])

print((1/2*A)+(3*B))

[[  9.5 -11. ]
 [ 23.    2. ]]
